name: Setup Node.js with cache
description: Setup Node.js and enable npm cache for faster installs

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '22'
  cache-dependency-path:
    description: Path(s) used to compute cache key (e.g. vue/package-lock.json)
    required: false
    default: 'vue/package-lock.json'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Show Node/npm versions
      shell: bash
      run: |
        node -v
        npm -v
