# Generated by Django 6.0.4 on 2026-04-29 08:34

import django.db.models.deletion
import nside_wefa.attachments.models.attachment
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Stable identifier shared across all versions of one logical attachment.",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing revision counter within an attachment_uid.",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True for the most recent revision of this attachment_uid.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The stored file blob.",
                        max_length=512,
                        upload_to=nside_wefa.attachments.models.attachment._attachment_upload_to,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Sanitised original filename, for display.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="MIME type as detected from the file bytes (not the client header).",
                        max_length=128,
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        help_text="Verified size in bytes after streaming."
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hex digest computed by streaming the file through `hash_algorithm`.",
                        max_length=128,
                    ),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        default="sha256",
                        help_text="Algorithm used for `file_hash`.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the upload, when known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "abstract": False,
            },
        ),
    ]
