// This file is auto-generated by @hey-api/openapi-ts

export type GetHello1Data = {
  body?: never
  path?: never
  query?: never
  url: '/basic-get'
}

export type GetHello1Responses = {
  /**
   * Empty response
   */
  200: {
    [key: string]: unknown
  }
}

export type GetHello1Response = GetHello1Responses[keyof GetHello1Responses]

export type GetHello2Data = {
  body?: never
  path?: never
  query: {
    name: string
  }
  url: '/simple-get'
}

export type GetHello2Responses = {
  /**
   * Simple string response
   */
  200: {
    greeting: string
  }
}

export type GetHello2Response = GetHello2Responses[keyof GetHello2Responses]

export type GetHello3Data = {
  body?: never
  path: {
    userId: number
  }
  query?: {
    verbose?: boolean
  }
  url: '/complex-get/{userId}'
}

export type GetHello3Responses = {
  /**
   * Complex object response
   */
  200: {
    user: {
      id?: number
      name?: string
      details?: {
        age?: number
        email?: string
      }
    }
    status: string
  }
}

export type GetHello3Response = GetHello3Responses[keyof GetHello3Responses]

export type PostHello1Data = {
  body?: never
  path?: never
  query?: never
  url: '/basic-post'
}

export type PostHello1Responses = {
  /**
   * Empty response
   */
  201: {
    [key: string]: unknown
  }
}

export type PostHello1Response = PostHello1Responses[keyof PostHello1Responses]

export type PostHello2Data = {
  body?: never
  path?: never
  query: {
    value: number
  }
  url: '/simple-post'
}

export type PostHello2Responses = {
  /**
   * Simple numeric response
   */
  201: {
    result: number
  }
}

export type PostHello2Response = PostHello2Responses[keyof PostHello2Responses]

export type PostHello3Data = {
  body: {
    meta: {
      timestamp?: string
      tags?: Array<string>
    }
    payload: {
      data?: string
      count?: number
    }
  }
  path: {
    itemId: number
  }
  query?: never
  url: '/complex-post/{itemId}'
}

export type PostHello3Responses = {
  /**
   * Complex object response
   */
  201: {
    item: {
      id?: number
      processed?: boolean
      summary?: string
    }
    info: {
      createdAt?: string
      notes?: Array<string>
    }
  }
}

export type PostHello3Response = PostHello3Responses[keyof PostHello3Responses]

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}
