name: Setup Python with pip cache and install
description: Setup Python, enable pip cache, upgrade pip, and install dependencies

inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.12'
  cache-dependency-path:
    description: Path(s) used to compute pip cache key (e.g. requirements.txt or pyproject.toml)
    required: false
    default: 'pyproject.toml'
  install-dev:
    description: Install development dependencies using extras ([dev])
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install dependencies (dev)
      if: ${{ inputs.install-dev == 'true' }}
      shell: bash
      run: pip install -e .[dev]

    - name: Install dependencies
      if: ${{ inputs.install-dev != 'true' }}
      shell: bash
      run: pip install -e .
