words:
  - wefa
  - autodocs
  - viewports
  - sonarjs
  - autorouted
  - primevue
  - primeuix
  - relaunchable
  - plotly
  - wefa
  - unhardcode
  - xaxis
  - yaxis
  - nside
  - codegen
  - vnode
ignorePaths:
  - 'src/demo/**/*'
  - 'src/demo.ts'
  - 'src/main.ts'
  - 'src/**/__tests__/**/*'
  - 'src/**/*.stories.ts'
  - 'src/**/*.vue'
  - 'src/**/*.spec.ts'