name: Django CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

# Run all steps from the Django app directory by default
defaults:
  run:
    working-directory: django

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and install deps
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.12'
          install-dev: 'true'
      - name: Dependency Check
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: django

  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and install deps
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.12'
          install-dev: 'true'

      - name: Ruff - static analysis
        run: uv run ruff check .

      - name: Ruff - formatting check
        run: uv run ruff format --check .

  type:
    name: Mypy Type Check
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      DJANGO_SETTINGS_MODULE: demo.settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and install deps
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.12'
          install-dev: 'true'

      - name: Run mypy
        run: uv run mypy --install-types --non-interactive .

  tests:
    name: Django Tests
    runs-on: ubuntu-latest
    needs: [lint, type]
    env:
      DJANGO_SETTINGS_MODULE: demo.settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and install deps
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.12'
          install-dev: 'true'

      - name: Migrate (SQLite)
        run: python manage.py migrate --noinput

      - name: Run tests (pytest + coverage)
        run: uv run pytest --cov-config=.coveragerc --cov-report xml --cov .

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: django/coverage.xml
          if-no-files-found: warn

  migrations-sanity:
    name: Migrations Sanity Check
    runs-on: ubuntu-latest
    needs: [lint, type]
    env:
      DJANGO_SETTINGS_MODULE: demo.settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and install deps
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.12'
          install-dev: 'true'

      - name: Check for pending migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Show migration plan
        run: python manage.py migrate --plan

      - name: Apply migrations
        run: python manage.py migrate --noinput
