name: Release
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-npm:
    name: Publish Vue package to npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js (with cache)
        uses: ./.github/actions/setup-node
        with:
          node-version: '20'
          cache-dependency-path: 'vue/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build --if-present

      - name: Configure npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "$NPM_TOKEN"
          npm whoami || true

      - name: Publish to npm
        env:
          NPM_CONFIG_PROVENANCE: 'true'
        run: npm publish --access public

  publish-pypi:
    name: Publish Django package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nside-wefa
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: django
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python and create venv (uv)
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.12'
          install-dev: 'false'
          project-dir: 'django'
          cache-dependency-path: 'django/pyproject.toml'

      - name: Install build tooling
        run: uv pip install --python "$VIRTUAL_ENV" build

      - name: Build distributions
        run: uv run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: django/dist
          skip-existing: true
